image: node:latest

stages:
    - build
    - deploy
    
build:
    stage: build
    environment: Production
    only:
        - master
    script:
        - npm install
        - npm run build
    artifacts:
        paths:
            - build/
            - firebase.json
            - .firebaserc

deploy:
    stage: deploy
    environment: Production
    only:
        - master
    script:
        - npm install -g firebase-tools
        - firebase use --token $FIREBASE_DEPLOY_KEY sdcalculatorweb
        - firebase deploy --token $FIREBASE_DEPLOY_KEY -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID"
    
