image: node:latest

stages:
    - deploy
    
deploy_sdcalculator:
    stage: deploy
    environment: Production
    only:
        - master
    script:
        - npm install -g firebase-tools
        - npm install
        - npm run build
        - firebase use --token $FIREBASE_DEPLOY_KEY sdcalculatorweb
        - firebase deploy --token $FIREBASE_DEPLOY_KEY -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID"
