default:
    image: node:latest

stages:
    - build
    - deploy
    
build:
    stage: build
    only:
        - master
    script:
        - npm install
        - echo "FIREBASE_API_KEY=$FIREBASE_API_KEY" >> .env
        - echo "FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN" >> .env
        - echo "FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL" >> .env
        - echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> .env
        - echo "FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET" >> .env
        - echo "FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID" >> .env
        - echo "FIREBASE_APP_ID=$FIREBASE_APP_ID" >> .env
        - npm run build
    artifacts:
        paths:
            - dist/
            - firebase.json
            - .firebaserc

deploy:
    stage: deploy
    only:
        - master
    script:
        - npm install -g firebase-tools
        - firebase use --token $FIREBASE_DEPLOY_KEY sdcalculus
        - firebase deploy --token $FIREBASE_DEPLOY_KEY -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID"
    
