default:
    image: node:latest

stages:
    - build
    - deploy
    
build:
    stage: build
    environment:
        API_KEY: $API_KEY
        AUTH_DOMAIN: $AUTH_DOMAIN
        DATABASE_URL: $DATABASE_URL
        PROJECT_ID: $PROJECT_ID
        STORAGE_BUCKET: $STORAGE_BUCKET
        MESSAGING_SENDER_ID: $MESSAGING_SENDER_ID
        APP_ID: $APP_ID
        MEASUREMENT_ID: $MEASUREMENT_ID

    only:
        - master
    script:
        - npm install
        - npm run build
    artifacts:
        paths:
            - dist/
            - firebase.json
            - .firebaserc

deploy:
    stage: deploy
    only:
        - master
    script:
        - npm install -g firebase-tools
        - firebase use --token $FIREBASE_DEPLOY_KEY sdcalculatorweb
        - firebase deploy --token $FIREBASE_DEPLOY_KEY -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID"
    
