default:
    image: node:latest

stages:
    - build
    - deploy
    
build:
    stage: build
    environment: production
    only:
        - master
    script:
        - npm install
        - echo "API_KEY=$API_KEY" >> ~/.env
        - echo "AUTH_DOMAIN=$AUTH_DOMAIN" >> ~/.env
        - echo "DATABASE_URL=$DATABASE_URL" >> ~/.env
        - echo "PROJECT_ID=$PROJECT_ID" >> ~/.env
        - echo "STORAGE_BUCKET=$STORAGE_BUCKET" >> ~/.env
        - echo "MESSAGING_SENDER_ID=$MESSAGING_SENDER_ID" >> ~/.env
        - echo "APP_ID=$APP_ID" >> .env
        - echo "MEASUREMENT_ID=$MEASUREMENT_ID" >> ~/.env
        - npm run build
    artifacts:
        paths:
            - dist/
            - firebase.json
            - .firebaserc

deploy:
    stage: deploy
    only:
        - master
    script:
        - npm install -g firebase-tools
        - firebase use --token $FIREBASE_DEPLOY_KEY sdcalculatorweb
        - firebase deploy --token $FIREBASE_DEPLOY_KEY -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID"
    
