# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SDCalculatorWeb CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Run Tests
      run: npm test
    - name: Build
      shell: bash
      env:
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      run: |
        echo "FIREBASE_API_KEY=$FIREBASE_API_KEY" >> .env
        echo "FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN" >> .env
        echo "FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL" >> .env
        echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> .env
        echo "FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET" >> .env
        echo "FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID" >> .env
        echo "FIREBASE_APP_ID=$FIREBASE_APP_ID" >> .env
        npm run build
    - name: Publish
      shell: bash
      env:
        FIREBASE_DEPLOY_KEY: ${{ secrets.FIREBASE_DEPLOY_KEY }}
      run: |
        npm install -g firebase-tools
        firebase use --token $FIREBASE_DEPLOY_KEY sdcalculus
        firebase deploy --token $FIREBASE_DEPLOY_KEY -m "Pipeline $GITHUB_WORKFLOW, build $GITHUB_RUN_ID"
