# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SDCalculatorWeb CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Run Tests
      run: npm test
    - name: Build
      shell: bash
      env:
        FIREBASE_API_KEY: ${{ secrets.SuperSecret }}
        FIREBASE_AUTH_DOMAIN: ${{ secrets.SuperSecret }}
        FIREBASE_DATABASE_URL: ${{ secrets.SuperSecret }}
        FIREBASE_PROJECT_ID: ${{ secrets.SuperSecret }}
        FIREBASE_STORAGE_BUCKET: ${{ secrets.SuperSecret }}
        FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.SuperSecret }}
        FIREBASE_APP_ID: ${{ secrets.SuperSecret }}
        FIREBASE_DEPLOY_KEY: ${{ secrets.SuperSecret }}
      run: |
        npm run build
    - name: Publish
      run: |
        npm install -g firebase-tools
        firebase use --token $FIREBASE_DEPLOY_KEY sdcalculus
        firebase deploy --token $FIREBASE_DEPLOY_KEY -m "Pipeline $GITHUB_WORKFLOW, build $GITHUB_RUN_ID"
